FROM cwds/ruby:11
ENV ENVIRONMENT_REFRESH 2017-10-11
ENV CANS_BASE_PATH /cans

RUN mkdir /app
WORKDIR /app
ADD Gemfile Gemfile.lock package.json /app/
RUN bundle install --jobs 20 --retry 5
RUN yarn install
