FROM selenium/node-chrome:3.13.0

USER root

RUN apt-get update && apt-get install -y curl
RUN curl https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip -o /usr/local/bin/chromedriver
RUN chmod +x /usr/local/bin/chromedriver

RUN apt-get update && apt-get install -y git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev xvfb
RUN apt-get install -y software-properties-common python-software-properties
RUN apt-add-repository ppa:brightbox/ruby-ng && apt-get update
RUN apt-get install -y ruby2.5-dev ruby2.5
RUN mkdir /app
WORKDIR app
ADD Gemfile Gemfile.lock /app/
RUN gem install bundler && bundle install
RUN chromedriver-update



