export const data = {
  date_info: [
    { date: '10/10/2016', status: '' },
    { date: '04/11/2017', status: '' },
    { date: '10/24/2017', status: '' },
    { date: '10/24/2017', status: '' },
    { date: '10/15/2018', status: 'IN_PROGRESS' },
  ],
  domains: [
    {
      code: 'ECH',
      under_six: true,
      above_six: false,
      ratting_totals: [13, 13, 12, 12, 11],
      items: [
        {
          under_six_id: 'EC01',
          above_six_id: '',
          code: 'IMPULSIVITY_HYPERACTIVITY',
          item_ratings: [
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
          ],
        },
        {
          under_six_id: 'EC02',
          above_six_id: '',
          code: 'DEPRESSION',
          item_ratings: [
            { value: '4', trend: '' },
            { value: '4', trend: '' },
            { value: '4', trend: '' },
            { value: '4', trend: '' },
            { value: '5', trend: 'down' },
          ],
        },
        {
          under_six_id: 'EC03',
          above_six_id: '',
          code: 'ANXIETY',
          item_ratings: [
            { value: '0', trend: '' },
            { value: '0', trend: '' },
            { value: '0', trend: '' },
            { value: '0', trend: '' },
            { value: '0', trend: '' },
          ],
        },
        {
          under_six_id: 'EC04',
          above_six_id: '',
          code: 'OPPOSITIONAL',
          item_ratings: [
            { value: '3', trend: '' },
            { value: '3', trend: '' },
            { value: '3', trend: '' },
            { value: '3', trend: '' },
            { value: '3', trend: '' },
          ],
        },
        {
          under_six_id: 'EC05',
          above_six_id: '',
          code: 'ADJUSTMENT_TO_TRAUMA',
          item_ratings: [
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
          ],
        },
        {
          under_six_id: 'EC06',
          above_six_id: '',
          code: 'ATTACHMENT_DIFFICULTIES',
          item_ratings: [
            { value: '0', trend: '' },
            { value: '0', trend: '' },
            { value: '0', trend: '' },
            { value: '0', trend: '' },
            { value: '0', trend: '' },
          ],
        },
        {
          under_six_id: 'EC07',
          above_six_id: '',
          code: 'REGULATORY',
          item_ratings: [
            { value: '3', trend: '' },
            { value: '3', trend: '' },
            { value: '2', trend: 'down' },
            { value: '3', trend: 'up' },
            { value: '3', trend: '' },
          ],
        },
        {
          under_six_id: 'EC08',
          above_six_id: '',
          code: 'ATYPICAL_BEHAVIORS',
          item_ratings: [
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
          ],
        },
        {
          under_six_id: 'EC09',
          above_six_id: '',
          code: 'SLEEP_CHILD',
          item_ratings: [
            { value: '0', trend: '' },
            { value: '0', trend: '' },
            { value: '0', trend: '' },
            { value: '0', trend: '' },
            { value: '0', trend: '' },
          ],
        },
      ],
    },
    {
      code: 'EFX',
      under_six: true,
      above_six: false,
      ratting_totals: [12, 12, 14, 16, 14],
      items: [
        {
          under_six_id: 'EC10',
          above_six_id: '',
          code: 'FAMILY_FUNCTIONING',
          item_ratings: [
            { value: '1', trend: '' },
            { value: '2', trend: 'up' },
            { value: '3', trend: 'up' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
          ],
        },
        {
          under_six_id: 'EC11',
          above_six_id: '',
          code: 'EARLY_EDUCATION',
          item_ratings: [
            { value: '4', trend: '' },
            { value: '4', trend: '' },
            { value: '1', trend: 'down' },
            { value: '4', trend: '' },
            { value: '5', trend: 'down' },
          ],
        },
        {
          under_six_id: 'EC12',
          above_six_id: '',
          code: 'SOCIAL_EMOTIONAL_FUNCTIONING',
          item_ratings: [
            { value: '0', trend: '' },
            { value: '0', trend: '' },
            { value: '0', trend: '' },
            { value: '1', trend: 'up' },
            { value: '0', trend: '' },
          ],
        },
        {
          under_six_id: 'EC13',
          above_six_id: '',
          code: 'DEVELOPMENTAL_INTELLECTUAL',
          item_ratings: [
            { value: '3', trend: '' },
            { value: '1', trend: 'down' },
            { value: '3', trend: 'up' },
            { value: '2', trend: 'down' },
            { value: '3', trend: '' },
          ],
        },
        {
          under_six_id: 'EC14',
          above_six_id: '',
          code: 'MEDICAL_PHYSICAL',
          item_ratings: [
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '0', trend: 'down' },
          ],
        },
      ],
    },
    {
      code: 'ERB',
      under_six: true,
      above_six: false,
      ratting_totals: [13, 13, 12, 12, 11],
      items: [
        {
          under_six_id: 'EC15',
          above_six_id: '',
          code: 'SELF_HARM',
          item_ratings: [
            { value: '0', trend: '' },
            { value: '1', trend: 'up' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
          ],
        },
        {
          under_six_id: 'EC16',
          above_six_id: '',
          code: 'EXPLOITED',
          item_ratings: [
            { value: '4', trend: '' },
            { value: '4', trend: '' },
            { value: '2', trend: 'down' },
            { value: '4', trend: 'up' },
            { value: '5', trend: 'down' },
          ],
        },
        {
          under_six_id: 'EC17',
          above_six_id: '',
          code: 'PRENATAL_CARE',
          item_ratings: [
            { value: '0', trend: '' },
            { value: '0', trend: '' },
            { value: '0', trend: '' },
            { value: '1', trend: 'up' },
            { value: '0', trend: 'down' },
          ],
        },
        {
          under_six_id: 'EC18',
          above_six_id: '',
          code: 'EXPOSURE',
          item_ratings: [
            { value: '3', trend: '' },
            { value: '3', trend: '' },
            { value: '0', trend: 'down' },
            { value: '3', trend: 'up' },
            { value: '3', trend: '' },
          ],
        },
        {
          under_six_id: 'EC19',
          above_six_id: '',
          code: 'LABOR_DELIVERY',
          item_ratings: [
            { value: '0', trend: '' },
            { value: '1', trend: 'up' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
          ],
        },
        {
          under_six_id: 'EC20',
          above_six_id: '',
          code: 'BIRTH_WEIGHT',
          item_ratings: [
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '3', trend: 'up' },
            { value: '1', trend: 'down' },
            { value: '1', trend: '' },
          ],
        },
        {
          under_six_id: 'EC21',
          above_six_id: '',
          code: 'FAILURE_TO_THRIVE',
          item_ratings: [
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
            { value: '1', trend: '' },
          ],
        },
      ],
    },
  ],
}
