export const LOCAL_DATE_FORMAT = 'MM/DD/YYYY'
export const ISO_DATE_FORMAT = 'YYYY-MM-DD'
export const VALID_ASSESSMENT_DATE_FORMATS = [
  'MM/DD/YYYY',
  'M/DD/YYYY',
  'MM/D/YYYY',
  'M/D/YYYY',
  'MM/DD/YY',
  'M/DD/YY',
  'MM/D/YY',
  'M/D/YY',
]
export const DEFAULT_AUTO_HIDE_TIMEOUT = 8000
export const TIMEOUT_EVENT = 'TIMEOUT_EVENT'
export const SESSION_EXPIRATION_WARNING_TIME = 300000 // 5 minutes
export const BRAND_NAME = 'CWS-CARES'

export const navigation = Object.freeze({
  STAFF_LIST: 'STAFF_LIST',
  STAFF_READ: 'STAFF_READ',
  STAFF_CHILD_PROFILE: 'STAFF_CHILD_PROFILE_OVERALL',
  STAFF_ASSESSMENT_EDIT: 'STAFF_ASSESSMENT_EDIT',
  STAFF_ASSESSMENT_ADD: 'STAFF_ASSESSMENT_ADD',
  STAFF_CHANGELOG: 'STAFF_CHANGELOG',

  CHILD_LIST: 'CHILD_LIST',
  CHILD_PROFILE: 'CHILD_PROFILE_OVERALL',

  ASSESSMENT_ADD: 'ASSESSMENT_ADD',
  ASSESSMENT_EDIT: 'ASSESSMENT_EDIT',

  CLIENT_SEARCH: 'CLIENT_SEARCH',
  SEARCH_ASSESSMENT_EDIT: 'SEARCH_ASSESSMENT_EDIT',
  SEARCH_CHILD_PROFILE: 'SEARCH_CHILD_PROFILE_OVERALL',
  SEARCH_ASSESSMENT_ADD: 'SEARCH_ASSESSMENT_ADD',
  SEARCH_CHANGELOG: 'SEARCH_CHANGELOG',

  ASSESSMENT_CHANGELOG: 'ASSESSMENT_CHANGELOG',
})

export const BreadCrumbLinks = Object.freeze({
  CLIENT_LIST: 'Client List',
  CANS_ASSESSMENT_FORM: 'CANS Assessment Form',
  STAFF_LIST: 'Staff List',
  ASSIGNED_STAFF: 'Assigned Staff',
  CLIENT_SEARCH: 'Client Search',
  CLIENT_PROFILE: 'Client, Name',
})

export const ClientStatus = Object.freeze({
  IN_PROGRESS: 'In progress',
  COMPLETED: 'Completed',
  NO_PRIOR_CANS: 'No prior CANS',
})

export const permissions = Object.freeze({
  SUBORDINATES_READ: 'CANS-staff-person-subordinates-read',
  CLIENTS_READ: 'CANS-staff-person-clients-read',
  CLIENT_SEARCH: 'CANS-client-search',
})

export const dashboards = Object.freeze({
  CHILD_LIST: 'CHILD_LIST',
  CLIENT_SEARCH: 'CLIENT_SEARCH',
  STAFF_LIST: 'STAFF_LIST',
})
