export const LOCAL_DATE_FORMAT = 'MM/DD/YYYY'
export const ISO_DATE_FORMAT = 'YYYY-MM-DD'
export const DEFAULT_AUTO_HIDE_TIMEOUT = 3000
export const TIMEOUT_EVENT = 'TIMEOUT_EVENT'
export const SESSION_EXPIRATION_WARNING_TIME = 5 * 60 * 1000 // 5 minutes

export const navigation = Object.freeze({
  CHILD_LIST: 'CHILD_LIST',
  CHILD_PROFILE: 'CHILD_PROFILE',
  CHILD_PROFILE_EDIT: 'CHILD_PROFILE_EDIT',
  CHILD_PROFILE_ADD: 'CHILD_PROFILE_ADD',
  ASSESSMENT_ADD: 'ASSESSMENT_ADD',
  ASSESSMENT_EDIT: 'ASSESSMENT_EDIT',
  STAFF_LIST: 'STAFF_LIST',
})

export const ClientStatus = Object.freeze({
  IN_PROGRESS: 'In progress',
  COMPLETED: 'Completed',
  NO_PRIOR_CANS: 'No prior CANS',
})
